### ISSUE TITLE
File Structure Change for TS compatibility.

### ISSUE THREAD

**Issue by 7ranceaddic7** [blackheart612/AirplanePlus#10]
Issue create to facilitate change.

Background: Spaces in Folder and File names are considered "unholy characters" and require massaging in TweakScale.  By replacing a space with an underscore ( _ ), "unholy characters" are avoided and re-aligns names with KSP naming convention - unbroken strings.

(Squad has violated this convention on one occasion that I know of but it was a mistake.)

**Comment by 7ranceaddic7** [comment]
Now, with this here you have an issue that can be referenced for a change made.

Pull Requests are changes submitted by other individuals to make changes to your repository as it is the origin for any forks (like mine.)

I make changes to my repository.  I test my changes against my repository.  When I'm satisfied, I submit a PR with my changes for you to review and either accept or deny.

PR coming next.

**Comment by blackheart612** [comment]
Merged. Will monitor for future problems. Sorry for the late notice, I didn't know.
