### ISSUE TITLE
missing smokePoint transform in raptorjet model

### ISSUE THREAD

**Issue by BrettRyland** [blackheart612/AirplanePlus#12]
Hi,

I'm seeing quite a few of the following entries in the KSP.log file
```[ERR 00:27:27.813] PrefabParticleFX: Cannot find transform of name 'smokePoint'```

This appears to be due to the `GameData/AirplanePlus/Parts/Engine/Modern/raptorjet/model.mu` lacking the `smokePoint` transform (the other models have it), which is used in the `PREFAB_PARTICLE` sections of the `EFFECTS` section of the raptorjet part.cfg file.

Could the model be updated to include this transform? Thanks!

**Comment by BrettRyland** [comment]
I got SuicidalInsanity to add the transform to the model. I've attached it as a zip file.
[model.mu.zip](https://github.com/blackheart612/AirplanePlus/files/6556073/model.mu.zip)

**Comment by blackheart612** [comment]
Thanks, tested and added in.
