### ISSUE TITLE
DXT3 textures not supported.

### ISSUE THREAD

**Issue by 7ranceaddic7** [blackheart612/AirplanePlus#9]
[LOG 20:10:32.048] Load(Texture): AirplanePlus/Parts/Utility/Skid/skidtex
[ERR 20:10:32.054] DDS: DXT3(256x256, MipMap=True) - DXT3 format is NOT supported. Use DXT5
[WRN 20:10:32.054] Texture load error in 'C:\Games\Kerbal Space Program\KSPwin64-1.9.1\GameData\AirplanePlus\Parts\Utility\Skid\skidtex.dds'

**Comment by blackheart612** [comment]
I didn't test it, but I reexported a new texture, it should be DXT5 dds now, inform me again if it doesn't work/still throws errors.

**Comment by 7ranceaddic7** [comment]
Bingo Bango.  That did it.  Thanks.
